services:
  database:
    container_name: bs-db
    build:
      context: ./database/Docker
      dockerfile: db.Dockerfile
    ports:
      - 5554:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgrespassword

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./database/data/var/pgdata:/var/lib/postgresql/data
    ports:
      - 4000:4000
